<?php
session_start();
if (!isset($_SESSION['login_id'])) {
    header("Location: login.php");
    exit;
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports - LogTrack Admin</title>
      <link rel="icon" type="image/png" href="../assets/img/denr-logo.png">
    <link rel="stylesheet" href="../assets/css/style.css"> <!-- main admin style -->
    <link rel="stylesheet" href="../assets/css/reports.css"> <!-- reports-specific style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
<div class="layout">
    <!-- Sidebar -->
    <?php include 'sidebar.php'; ?>

    <!-- Main Wrapper -->
    <div class="main-wrapper" id="mainWrapper">
        <!-- Header -->
        <header>
            <div class="header-content">
                <span class="menu-icon" onclick="toggleSidebar()">☰</span>
                <h2>Reports</h2>
            </div>
        </header>

        <!-- Page Content -->
        <div class="content">
            <div class="page-header">
                <h3>Reports</h3>
                <p>Generate and view system reports</p>
            </div>

            <!-- Report Categories -->
            <div class="report-cards">
                <div class="report-card">
                    <h3>Log Case Reports</h3>
                    <p>Summary of log apprehensions and disposals.</p>
                    <a href="generate_report.php?type=logcase" class="btn-generate">Generate</a>
                </div>

<div class="report-card">
    <h3>Seedling Reports</h3>
    <p>Summary of seedling inventory and distributions.</p>
    <a href="generate_report.php?type=seedling" class="btn-generate">Generate</a>
</div>


                <div class="report-card">
                    <h3>Staff Contribution Reports</h3>
                    <p>Summary of staff and personnel contributions.</p>
                    <a href="#" class="btn-generate">Generate</a>
                </div>
            </div>

            <!-- Reports History -->
            <div class="reports-history">
                <h3>Reports History</h3>
                <table class="reports-table">
                    <thead>
                        <tr>
                            <th>Report ID</th>
                            <th>Type</th>
                            <th>Date Generated</th>
                            <th>Generated By</th>
                            <th>Action</th>
                        </tr>
                    </thead>
<tbody>
<?php
include '../db_connect.php';
$result = $conn->query("SELECT * FROM reports_history ORDER BY date_generated DESC");

if ($result->num_rows > 0):
    while($row = $result->fetch_assoc()):
?>
    <tr>
        <td>#<?php echo $row['id']; ?></td>
        <td><?php echo ucfirst($row['type']); ?></td>
        <td><?php echo $row['date_generated']; ?></td>
        <td><?php echo $row['generated_by']; ?></td>
        <td>
            <a href="../reports/<?php echo $row['filename']; ?>" target="_blank" class="btn-view">View</a>
        </td>
    </tr>
<?php
    endwhile;
else:
?>
    <tr>
        <td colspan="5" style="text-align:center;">No reports generated yet.</td>
    </tr>
<?php endif; ?>
</tbody>

                </table>
            </div>
        </div>
    </div>
</div>

<!-- Sidebar Toggle Script -->
<script>
function toggleSidebar() {
    const sidebar = document.querySelector('.sidebar');
    const mainWrapper = document.getElementById('mainWrapper');
    sidebar.classList.toggle('active');
    mainWrapper.classList.toggle('shifted');
}
</script>

<?php include 'footer.php'; ?>
</body>
</html>
